package AngelYMilton.FMDataAnalisis.Enums;

public enum Posiciones {

    //PORTERO
    PORTERO_TRADICIONAL,
    PORTERO_LIBERO,
    //DEFENSAS CENTRALES
    CENTRAL_TRADICIONAL,
    CENTRAL_MODERNO,
    CENTRAL_LIBERO,

    CENTRAL_LATERAL,
    //LATERALES
    LATERAL,
    CARRILERO,
    CARILLERO_INVERSO,

    //EXTREMOS
    EXTREMO_BANDA,
    EXTREMO_INVERSO,
    ORGANIZADOR_BANDA,
    //CENTROCAMPISTAS
    PIVOTE_ORGANIZADOR,
    ORGANIZADOR_OFENSIVO,
    CENTROCAMPISTA_RECUPERADOR,
    PIVOTE_DEFENSIVO,
    BOX_TO_BOX,
    CENTROCAMPISTA_OFENSIVO,

    //ATAQUE
    DELANTERO_INTERIOR,
    MEDIAPUNTA,
    DELANTERO_RATON,
    DELANTERO_APOYO,
    DELANTERO_OBJETIVO,
    DELANTERO_AVANZADO,
    FALSO_9,
    DELANTERO_PRESION,
    ARIETE,
    DELANTERO_COMPLETO


}
